name: "BrowserStack Test"
on: [push, pull_request]

concurrency:
  group: browserstack
jobs:
  ubuntu-job:
    name: "BrowserStack Test on Ubuntu"
    runs-on: ubuntu-latest # Can be self-hosted runner also
    steps:
      - name: "BrowserStack Env Setup" # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

      - name: "BrowserStack Local Tunnel Setup" # Invokes the setup-local action
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: "start"
          local-logging-level: "all-logs"
          local-identifier: "random"

      # The next 3 steps are for building the web application to be tested and starting the web server on the runner environment

      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Building web application to be tested"
        run: npm install && npm run build

      - name: "Running application under test"
        run: npx http-server -p 3000 --cors &

      - name: "Running test on BrowserStack" # Invokes the actual test script that would run on BrowserStack browsers
        run: npm run e2e:bstack # See sample test script above

      - name: "BrowserStackLocal Stop" # Terminating the BrowserStackLocal tunnel connection
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: "stop"
